# ROBOT_TERMINAL_SERVER_CONFIG
ROBOT_TERMINAL_SERVER_HOST = '0.0.0.0'
ROBOT_TERMINAL_SERVER_UDP_PORT = 5001
ROBOT_TERMINAL_SERVER_HTTP_PORT = 5100

# Configuration for UGV Beast Pi5
ROBOT_TYPE = 'UGV_BEAST_PI5'
LOW_LEVEL_CONTROL_SERIAL_PORT = '/dev/ttyAMA0' # UGV_BEAST_PI5
LOW_LEVEL_CONTROL_BAUD_RATE = 115200

# TURRET Camera settings
TURRET_CAM_DEVICE_INDEX = 0
TURRET_CAM_WIDTH = 640
TURRET_CAM_HEIGHT = 480
TURRET_CAM_FPS_CAP = 30
TURRET_CAM_JPEG_QUALITY = 80
TURRET_CAM_FOV = 65

# TURRET Control settings
TURRET_HOR_MIN = -135 # UGV max is 180
TURRET_HOR_MAX = 135 # UGV max is -180
TURRET_VER_MIN = -25 # UGV max is -30
TURRET_VER_MAX = 45 # UGV max is 90
TURRET_HOR_CENTER = 0
TURRET_VER_CENTER = 0
TURRET_HOR_STEP_MAX = 20 # 10
TURRET_VER_STEP_MAX = 20 # 10
TURRET_SPEED = 0 # 300 UGV visual control /0 = max speed
TURRET_ACC = 0 # 500 # 300 # 0 = max acc
TURRET_AIM_TOLERANCE_PX = 50  # pixels
TURRET_AIM_SMOOTHING = 0.25  # 0.5 too much, 0.3 too much     # 0.0 to 1.0, higher is smoother but more laggy
TURRET_AIM_CMD_DELAY = 0.05


# BODY Control settings
BODY_DEFAULT_LINEAR_SPEED = 0.2  # Default speed in m/s
BODY_DEFAULT_TURN_SPEED = 0.2
BODY_DEFAULT_MOVE_DURATION = 0.5  # Default duration in seconds


